version: '3.1'

services:
    node-service:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/src/app
        ports:
            - '3000:3000'
        container_name: nodejs-service
